/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Projects */
        get: operations["list_projects_projects_get"];
        put?: never;
        /** Create Project */
        post: operations["create_project_projects_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{project_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Project */
        get: operations["get_project_projects__project_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Project */
        patch: operations["update_project_projects__project_id__patch"];
        trace?: never;
    };
    "/projects/{project_id}/folders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Root Folders
         * @description Top-level folders of a project (the folder tree's entry point).
         *
         *     Videos always live inside a folder, so a project's root contains only
         *     folders; deeper levels are fetched per-folder via ``GET /folders/{id}``.
         */
        get: operations["list_root_folders_projects__project_id__folders_get"];
        put?: never;
        /** Create Folder */
        post: operations["create_folder_projects__project_id__folders_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/folders/{folder_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Folder */
        get: operations["get_folder_folders__folder_id__get"];
        put?: never;
        post?: never;
        /** Delete Folder */
        delete: operations["delete_folder_folders__folder_id__delete"];
        options?: never;
        head?: never;
        /** Update Folder */
        patch: operations["update_folder_folders__folder_id__patch"];
        trace?: never;
    };
    "/folders/{folder_id}/videos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Upload Video */
        post: operations["upload_video_folders__folder_id__videos_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/videos/{video_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Video */
        get: operations["get_video_videos__video_id__get"];
        put?: never;
        post?: never;
        /** Delete Video */
        delete: operations["delete_video_videos__video_id__delete"];
        options?: never;
        head?: never;
        /** Update Video */
        patch: operations["update_video_videos__video_id__patch"];
        trace?: never;
    };
    "/videos/{video_id}/media-token": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Create Media Token
         * @description Mint a short-lived signed token for streaming this video's media.
         *
         *     The browser attaches it as ``?token=`` on the proxy stream, which a
         *     ``<video>`` element cannot authenticate with a Bearer header.
         */
        get: operations["create_media_token_videos__video_id__media_token_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/videos/{video_id}/proxy": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Stream Proxy
         * @description Stream the playback proxy (falling back to the original) with Range support.
         *
         *     Authorized by a signed ``?token=`` rather than a Bearer header. Starlette's
         *     ``FileResponse`` honors HTTP Range requests, so ``<video>`` seeking works.
         */
        get: operations["stream_proxy_videos__video_id__proxy_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/videos/{video_id}/thumbnail": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Thumbnail
         * @description Serve the generated thumbnail image, authorized by a signed ``?token=``.
         *
         *     Same media-token scheme as ``stream_proxy`` — this gets rendered as an
         *     ``<img src>`` across many videos on the search page.
         */
        get: operations["get_thumbnail_videos__video_id__thumbnail_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/videos/{video_id}/waveform": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Waveform
         * @description Return the precomputed waveform peaks JSON for the timeline display.
         *
         *     Fetched via the typed client (XHR/fetch can send a Bearer header), so this
         *     keeps the normal membership check rather than the media-token scheme.
         */
        get: operations["get_waveform_videos__video_id__waveform_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Job */
        get: operations["get_job_jobs__job_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs/{job_id}/retry": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Retry Job */
        post: operations["retry_job_jobs__job_id__retry_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/videos/{video_id}/transcripts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Transcripts */
        get: operations["list_transcripts_videos__video_id__transcripts_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/transcripts/{transcript_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Transcript */
        get: operations["get_transcript_transcripts__transcript_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/transcripts/{transcript_id}/translate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create Translation
         * @description Request a translation: enqueue the worker that produces it.
         *
         *     The long-running translation runs in the worker, never inline. The job
         *     carries the source transcript and target language; the worker builds a new
         *     translation transcript and leaves the source untouched.
         */
        post: operations["create_translation_transcripts__transcript_id__translate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/transcripts/{transcript_id}/reindex": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Reindex Transcript
         * @description Force an immediate full re-embed of this transcript.
         *
         *     Token edits already schedule a debounced re-embed automatically (see
         *     ``app/services/reembed.py``); this route is only needed to jump the
         *     queue — e.g. right before asking a question you need answered now, or
         *     after changing the embedding model/config for existing content.
         */
        post: operations["reindex_transcript_transcripts__transcript_id__reindex_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/videos/{video_id}/speakers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Speakers */
        get: operations["list_speakers_videos__video_id__speakers_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/speakers/{speaker_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Speaker */
        patch: operations["update_speaker_speakers__speaker_id__patch"];
        trace?: never;
    };
    "/tokens/{token_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Remove Token */
        delete: operations["remove_token_tokens__token_id__delete"];
        options?: never;
        head?: never;
        /** Update Token */
        patch: operations["update_token_tokens__token_id__patch"];
        trace?: never;
    };
    "/tokens/merge": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Merge */
        post: operations["merge_tokens_merge_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tokens/{token_id}/split": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Split */
        post: operations["split_tokens__token_id__split_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/transcripts/{transcript_id}/comments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Comments */
        get: operations["list_comments_transcripts__transcript_id__comments_get"];
        put?: never;
        /** Create */
        post: operations["create_transcripts__transcript_id__comments_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/documents/{document_id}/comments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List For Document */
        get: operations["list_for_document_documents__document_id__comments_get"];
        put?: never;
        /** Create For Document */
        post: operations["create_for_document_documents__document_id__comments_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/comments/{comment_id}/replies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reply */
        post: operations["reply_comments__comment_id__replies_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/comments/{comment_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update */
        patch: operations["update_comments__comment_id__patch"];
        trace?: never;
    };
    "/projects/{project_id}/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Search */
        get: operations["search_projects__project_id__search_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/transcripts/{transcript_id}/exports": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create Export
         * @description Request an export: record the row and enqueue the worker that renders it.
         */
        post: operations["create_export_transcripts__transcript_id__exports_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/exports/{export_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Export */
        get: operations["get_export_exports__export_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/exports/{export_id}/content": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Download Export */
        get: operations["download_export_exports__export_id__content_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{project_id}/members": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Project Members */
        get: operations["list_project_members_projects__project_id__members_get"];
        put?: never;
        /** Invite */
        post: operations["invite_projects__project_id__members_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{project_id}/members/{user_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Remove
         * @description Remove a member, or let a member remove (leave) themselves.
         *
         *     Removing *another* member requires ``OWNER``; removing yourself is always
         *     allowed (the service layer's last-owner guard still applies).
         */
        delete: operations["remove_projects__project_id__members__user_id__delete"];
        options?: never;
        head?: never;
        /** Change Role */
        patch: operations["change_role_projects__project_id__members__user_id__patch"];
        trace?: never;
    };
    "/projects/{project_id}/chat": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Conversations
         * @description A project's chat history, most recently active conversation first.
         */
        get: operations["list_conversations_projects__project_id__chat_get"];
        put?: never;
        /**
         * Ask
         * @description Ask a question over the project's transcripts; enqueues no job.
         *
         *     Streams server-sent events on the same request/response rather than a
         *     single JSON body: a ``status`` event each time the agent starts a search
         *     (so the UI can show "Searching for ..." live), then one terminal event —
         *     ``done`` with the persisted message, or ``error``.
         *
         *     A bad ``conversation_id`` is checked here, before the stream starts, so
         *     it can still be a normal 404 — once ``StreamingResponse`` sends headers
         *     (200), the status code can no longer change, so ``stream_answer_question``
         *     turns that same case into an ``error`` event instead as a defensive
         *     fallback (e.g. a delete racing this request).
         */
        post: operations["ask_projects__project_id__chat_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{project_id}/chat/{conversation_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Conversation */
        get: operations["get_conversation_projects__project_id__chat__conversation_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{project_id}/documents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Project Documents */
        get: operations["list_project_documents_projects__project_id__documents_get"];
        put?: never;
        /** Create */
        post: operations["create_projects__project_id__documents_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/documents/{document_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get */
        get: operations["get_documents__document_id__get"];
        put?: never;
        post?: never;
        /** Delete */
        delete: operations["delete_documents__document_id__delete"];
        options?: never;
        head?: never;
        /** Update */
        patch: operations["update_documents__document_id__patch"];
        trace?: never;
    };
    "/documents/{document_id}/clip-blocks/resolve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Resolve Clip Block Route
         * @description Lets the editor populate a newly inserted node's attrs immediately, without a
         *     full document round-trip. ``document`` only gates access — the clip itself can
         *     reference any transcript, since a clip's source video need not be the one
         *     the document is scoped to (documents are project-scoped, not video-scoped).
         */
        post: operations["resolve_clip_block_route_documents__document_id__clip_blocks_resolve_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AssetType
         * @enum {string}
         */
        AssetType: "original" | "proxy" | "waveform" | "thumbnail";
        /** Body_upload_video_folders__folder_id__videos_post */
        Body_upload_video_folders__folder_id__videos_post: {
            /** File */
            file: string;
        };
        /** ChatAskRequest */
        ChatAskRequest: {
            /** Question */
            question: string;
            /** Conversation Id */
            conversation_id?: string | null;
        };
        /**
         * ChatCitation
         * @description The persisted citation shape plus response-time-only display fields.
         *
         *     ``thumbnail_token`` and ``folder_path`` are never stored on
         *     ``ChatMessage.citations`` — like ``search.py``'s ``SearchVideoGroup``, a
         *     media token is short-lived and a breadcrumb can go stale, so both are
         *     computed fresh by the route on every read.
         */
        ChatCitation: {
            /** Marker */
            marker: number;
            /**
             * Chunk Id
             * Format: uuid
             */
            chunk_id: string;
            /**
             * Transcript Id
             * Format: uuid
             */
            transcript_id: string;
            /**
             * Video Id
             * Format: uuid
             */
            video_id: string;
            /** Video Name */
            video_name: string;
            /**
             * Segment Id
             * Format: uuid
             */
            segment_id: string;
            /**
             * Start Token Id
             * Format: uuid
             */
            start_token_id: string;
            /**
             * End Token Id
             * Format: uuid
             */
            end_token_id: string;
            /** Start Time */
            start_time: number;
            /** End Time */
            end_time: number;
            /** Speaker Name */
            speaker_name: string | null;
            /** Language */
            language: string | null;
            /** Excerpt */
            excerpt: string;
            /** Thumbnail Token */
            thumbnail_token: string | null;
            /** Folder Path */
            folder_path: string[];
        };
        /**
         * ChatConversationSummary
         * @description One row in a project's conversation history list — no messages.
         */
        ChatConversationSummary: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Title */
            title: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** ChatMessageRead */
        ChatMessageRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Role */
            role: string;
            /** Content */
            content: string;
            /** Citations */
            citations: components["schemas"]["ChatCitation"][] | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /**
         * ClipBlockRead
         * @description A clip block's resolved display fields, mirroring ``ChatCitation``.
         *
         *     Resolved fresh from the referenced tokens on every read — nothing here is
         *     persisted on ``Document.content``, so the excerpt can't drift from edits
         *     made to the source transcript.
         */
        ClipBlockRead: {
            /**
             * Transcript Id
             * Format: uuid
             */
            transcript_id: string;
            /**
             * Video Id
             * Format: uuid
             */
            video_id: string;
            /** Video Name */
            video_name: string;
            /**
             * Segment Id
             * Format: uuid
             */
            segment_id: string;
            /**
             * Start Token Id
             * Format: uuid
             */
            start_token_id: string;
            /**
             * End Token Id
             * Format: uuid
             */
            end_token_id: string;
            /** Start Time */
            start_time: number;
            /** End Time */
            end_time: number;
            /** Speaker Name */
            speaker_name: string | null;
            /** Language */
            language: string | null;
            /** Excerpt */
            excerpt: string;
            /** Thumbnail Token */
            thumbnail_token: string | null;
            /** Folder Path */
            folder_path: string[];
        };
        /** ClipBlockResolveRequest */
        ClipBlockResolveRequest: {
            /**
             * Transcript Id
             * Format: uuid
             */
            transcript_id: string;
            /**
             * Start Token Id
             * Format: uuid
             */
            start_token_id: string;
            /**
             * End Token Id
             * Format: uuid
             */
            end_token_id: string;
        };
        /** CommentCreate */
        CommentCreate: {
            /**
             * Start Token Id
             * Format: uuid
             */
            start_token_id: string;
            /**
             * End Token Id
             * Format: uuid
             */
            end_token_id: string;
            /** Text */
            text: string;
        };
        /** CommentRead */
        CommentRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Created By
             * Format: uuid
             */
            created_by: string;
            /** Text */
            text: string;
            /** Resolved */
            resolved: boolean;
            /** Anchor */
            anchor: components["schemas"]["TranscriptCommentAnchor"] | components["schemas"]["DocumentCommentAnchorRead"];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Replies */
            replies: components["schemas"]["CommentReplyRead"][];
        };
        /** CommentReplyCreate */
        CommentReplyCreate: {
            /** Text */
            text: string;
        };
        /** CommentReplyRead */
        CommentReplyRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Created By
             * Format: uuid
             */
            created_by: string;
            /** Text */
            text: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** CommentUpdate */
        CommentUpdate: {
            /** Resolved */
            resolved?: boolean | null;
        };
        /** DocumentCommentAnchorRead */
        DocumentCommentAnchorRead: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "document";
            /**
             * Document Id
             * Format: uuid
             */
            document_id: string;
            /** Clip Node Id */
            clip_node_id: string | null;
            /** Excerpt */
            excerpt: string | null;
        };
        /** DocumentCommentCreate */
        DocumentCommentCreate: {
            /** Clip Node Id */
            clip_node_id?: string | null;
            /** Text */
            text: string;
        };
        /** DocumentCreate */
        DocumentCreate: {
            /** Title */
            title: string;
        };
        /** DocumentRead */
        DocumentRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Project Id
             * Format: uuid
             */
            project_id: string;
            /** Title */
            title: string;
            /** Content */
            content: {
                [key: string]: unknown;
            };
            /** Version */
            version: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * DocumentSummary
         * @description List-view shape — no ``content``, keeping the panel's document switcher cheap.
         */
        DocumentSummary: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Title */
            title: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** DocumentUpdate */
        DocumentUpdate: {
            /** Title */
            title?: string | null;
            /** Content */
            content?: {
                [key: string]: unknown;
            } | null;
            /** Expected Version */
            expected_version: number;
        };
        /** ExportCreate */
        ExportCreate: {
            format: components["schemas"]["ExportType"];
        };
        /** ExportCreateResponse */
        ExportCreateResponse: {
            /**
             * Export Id
             * Format: uuid
             */
            export_id: string;
            /**
             * Processing Job Id
             * Format: uuid
             */
            processing_job_id: string;
        };
        /** ExportRead */
        ExportRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Transcript Id
             * Format: uuid
             */
            transcript_id: string;
            type: components["schemas"]["ExportType"];
            /** Ready */
            ready: boolean;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /**
         * ExportType
         * @enum {string}
         */
        ExportType: "markdown" | "srt";
        /** FolderContents */
        FolderContents: {
            folder: components["schemas"]["FolderRead"];
            /** Folders */
            folders: components["schemas"]["FolderRead"][];
            /** Videos */
            videos: components["schemas"]["VideoSummary"][];
        };
        /** FolderCreate */
        FolderCreate: {
            /** Name */
            name: string;
            /** Parent Folder Id */
            parent_folder_id?: string | null;
        };
        /** FolderRead */
        FolderRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Project Id
             * Format: uuid
             */
            project_id: string;
            /** Parent Folder Id */
            parent_folder_id: string | null;
            /** Name */
            name: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** FolderUpdate */
        FolderUpdate: {
            /** Name */
            name?: string | null;
            /** Parent Folder Id */
            parent_folder_id?: string | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** JobRead */
        JobRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Video Id */
            video_id: string | null;
            type: components["schemas"]["JobType"];
            status: components["schemas"]["JobStatus"];
            /** Progress */
            progress: number;
            /** Error Message */
            error_message: string | null;
            /** Result */
            result: {
                [key: string]: unknown;
            } | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Started At */
            started_at: string | null;
            /** Completed At */
            completed_at: string | null;
        };
        /**
         * JobStatus
         * @enum {string}
         */
        JobStatus: "pending" | "running" | "completed" | "failed";
        /**
         * JobType
         * @enum {string}
         */
        JobType: "extract_metadata" | "generate_proxy" | "generate_thumbnail" | "generate_waveform" | "extract_audio" | "transcribe" | "translate" | "generate_embeddings" | "export" | "noop";
        /** MediaTokenResponse */
        MediaTokenResponse: {
            /** Token */
            token: string;
            /** Expires In */
            expires_in: number;
        };
        /** MemberInvite */
        MemberInvite: {
            /** Email */
            email: string;
            role: components["schemas"]["MembershipRole"];
        };
        /** MemberRead */
        MemberRead: {
            /**
             * User Id
             * Format: uuid
             */
            user_id: string;
            /** Email */
            email: string;
            /** Display Name */
            display_name: string | null;
            role: components["schemas"]["MembershipRole"];
        };
        /** MemberRoleUpdate */
        MemberRoleUpdate: {
            role: components["schemas"]["MembershipRole"];
        };
        /**
         * MembershipRole
         * @description A member's permission tier on a project.
         *
         *     Kept on ``ProjectMembership`` (not named ``ProjectRole``) and the
         *     membership-check helpers kept composable so a future multi-tenant
         *     ``Organization`` layer can reuse the same shape without renaming this.
         * @enum {string}
         */
        MembershipRole: "owner" | "editor" | "viewer";
        /** ProjectCreate */
        ProjectCreate: {
            /** Name */
            name: string;
            /** Description */
            description?: string | null;
        };
        /** ProjectRead */
        ProjectRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** Description */
            description: string | null;
            /** Archived At */
            archived_at: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            my_role: components["schemas"]["MembershipRole"];
        };
        /** ProjectUpdate */
        ProjectUpdate: {
            /** Name */
            name?: string | null;
            /** Description */
            description?: string | null;
            /** Archived */
            archived?: boolean | null;
        };
        /** ReindexResponse */
        ReindexResponse: {
            /**
             * Job Id
             * Format: uuid
             */
            job_id: string;
        };
        /**
         * SearchHitRead
         * @description One matching location within a video, returned inside a ``SearchVideoGroup``.
         *
         *     ``kind`` is ``transcript`` (a token), ``speaker``, or ``comment``.
         *     ``start_time`` is the video position to seek to (``None`` for speaker
         *     matches, which are video-level).
         */
        SearchHitRead: {
            /** Kind */
            kind: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Transcript Id */
            transcript_id: string | null;
            /** Text */
            text: string;
            /** Start Time */
            start_time: number | null;
            /** Rank */
            rank: number;
        };
        /**
         * SearchResponse
         * @description A page of video groups, ranked by each group's best-hit rank descending.
         */
        SearchResponse: {
            /** Groups */
            groups: components["schemas"]["SearchVideoGroup"][];
            /** Total Videos */
            total_videos: number;
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
        };
        /**
         * SearchVideoGroup
         * @description All matches within a single video, with enough context to render a card.
         */
        SearchVideoGroup: {
            /**
             * Video Id
             * Format: uuid
             */
            video_id: string;
            /** Video Name */
            video_name: string;
            /** Folder Path */
            folder_path: string[];
            /** Thumbnail Token */
            thumbnail_token: string | null;
            /** Hits */
            hits: components["schemas"]["SearchHitRead"][];
            /** Hit Count */
            hit_count: number;
        };
        /** SegmentRead */
        SegmentRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Speaker Id */
            speaker_id: string | null;
            /** Tokens */
            tokens: components["schemas"]["TokenRead"][];
        };
        /** SpeakerRead */
        SpeakerRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Video Id
             * Format: uuid
             */
            video_id: string;
            /** Provider Identifier */
            provider_identifier: string | null;
            /** Name */
            name: string | null;
            /** Color */
            color: string | null;
        };
        /** SpeakerUpdate */
        SpeakerUpdate: {
            /** Name */
            name?: string | null;
            /** Color */
            color?: string | null;
        };
        /** TokenEdit */
        TokenEdit: {
            /** Edited Text */
            edited_text: string | null;
            /** Expected Version */
            expected_version: number;
        };
        /** TokenMergeItem */
        TokenMergeItem: {
            /**
             * Token Id
             * Format: uuid
             */
            token_id: string;
            /** Expected Version */
            expected_version: number;
        };
        /** TokenMergeRequest */
        TokenMergeRequest: {
            /** Tokens */
            tokens: components["schemas"]["TokenMergeItem"][];
            /** Text */
            text: string;
        };
        /** TokenRead */
        TokenRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Segment Id
             * Format: uuid
             */
            segment_id: string;
            /** Original Text */
            original_text: string;
            /** Edited Text */
            edited_text: string | null;
            /** Text */
            text: string;
            /** Start Time */
            start_time: number;
            /** End Time */
            end_time: number;
            /** Version */
            version: number;
        };
        /** TokenSplitPiece */
        TokenSplitPiece: {
            /** Text */
            text: string;
        };
        /** TokenSplitRequest */
        TokenSplitRequest: {
            /** Tokens */
            tokens: components["schemas"]["TokenSplitPiece"][];
            /** Expected Version */
            expected_version: number;
        };
        /** TranscriptCommentAnchor */
        TranscriptCommentAnchor: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "transcript";
            /**
             * Transcript Id
             * Format: uuid
             */
            transcript_id: string;
            /**
             * Start Token Id
             * Format: uuid
             */
            start_token_id: string;
            /**
             * End Token Id
             * Format: uuid
             */
            end_token_id: string;
            /** In Time */
            in_time: number;
            /** Out Time */
            out_time: number;
        };
        /** TranscriptRead */
        TranscriptRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Video Id
             * Format: uuid
             */
            video_id: string;
            /** Language */
            language: string | null;
            type: components["schemas"]["TranscriptType"];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Segments */
            segments: components["schemas"]["SegmentRead"][];
        };
        /** TranscriptSummary */
        TranscriptSummary: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Video Id
             * Format: uuid
             */
            video_id: string;
            /** Language */
            language: string | null;
            type: components["schemas"]["TranscriptType"];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /**
         * TranscriptType
         * @enum {string}
         */
        TranscriptType: "original" | "translation";
        /** TranslationCreate */
        TranslationCreate: {
            /** Target Language */
            target_language: string;
        };
        /** TranslationResponse */
        TranslationResponse: {
            /**
             * Job Id
             * Format: uuid
             */
            job_id: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** VideoAssetRead */
        VideoAssetRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            type: components["schemas"]["AssetType"];
            /** Storage Path */
            storage_path: string;
            /** Mime Type */
            mime_type: string | null;
            /** Size */
            size: number | null;
        };
        /** VideoJobRead */
        VideoJobRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            type: components["schemas"]["JobType"];
            status: components["schemas"]["JobStatus"];
            /** Progress */
            progress: number;
            /** Error Message */
            error_message: string | null;
        };
        /** VideoRead */
        VideoRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Folder Id
             * Format: uuid
             */
            folder_id: string;
            /**
             * Project Id
             * Format: uuid
             */
            project_id: string;
            /** Name */
            name: string;
            /** Original Filename */
            original_filename: string;
            /** Duration */
            duration: number | null;
            /** Frame Rate */
            frame_rate: number | null;
            /** Width */
            width: number | null;
            /** Height */
            height: number | null;
            /** Assets */
            assets: components["schemas"]["VideoAssetRead"][];
            /** Jobs */
            jobs: components["schemas"]["VideoJobRead"][];
            /** Folder Path */
            folder_path: string[];
        };
        /** VideoSummary */
        VideoSummary: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
        };
        /** VideoUpdate */
        VideoUpdate: {
            /** Folder Id */
            folder_id?: string | null;
        };
        /** VideoUploadResponse */
        VideoUploadResponse: {
            /**
             * Video Id
             * Format: uuid
             */
            video_id: string;
            /**
             * Processing Job Id
             * Format: uuid
             */
            processing_job_id: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    list_projects_projects_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectRead"][];
                };
            };
        };
    };
    create_project_projects_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProjectCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_project_projects__project_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_project_projects__project_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProjectUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_root_folders_projects__project_id__folders_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FolderRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_folder_projects__project_id__folders_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FolderCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FolderRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_folder_folders__folder_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                folder_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FolderContents"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_folder_folders__folder_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                folder_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_folder_folders__folder_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                folder_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FolderUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FolderRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upload_video_folders__folder_id__videos_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                folder_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_video_folders__folder_id__videos_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VideoUploadResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_video_videos__video_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                video_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VideoRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_video_videos__video_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                video_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_video_videos__video_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                video_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VideoUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VideoRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_media_token_videos__video_id__media_token_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                video_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MediaTokenResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stream_proxy_videos__video_id__proxy_get: {
        parameters: {
            query: {
                token: string;
            };
            header?: never;
            path: {
                video_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_thumbnail_videos__video_id__thumbnail_get: {
        parameters: {
            query: {
                token: string;
            };
            header?: never;
            path: {
                video_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_waveform_videos__video_id__waveform_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                video_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_job_jobs__job_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    retry_job_jobs__job_id__retry_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_transcripts_videos__video_id__transcripts_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                video_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TranscriptSummary"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_transcript_transcripts__transcript_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                transcript_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TranscriptRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_translation_transcripts__transcript_id__translate_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                transcript_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TranslationCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TranslationResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reindex_transcript_transcripts__transcript_id__reindex_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                transcript_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReindexResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_speakers_videos__video_id__speakers_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                video_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SpeakerRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_speaker_speakers__speaker_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                speaker_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SpeakerUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SpeakerRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    remove_token_tokens__token_id__delete: {
        parameters: {
            query: {
                expected_version: number;
            };
            header?: never;
            path: {
                token_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_token_tokens__token_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                token_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TokenEdit"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    merge_tokens_merge_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TokenMergeRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    split_tokens__token_id__split_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                token_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TokenSplitRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_comments_transcripts__transcript_id__comments_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                transcript_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CommentRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_transcripts__transcript_id__comments_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                transcript_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CommentCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CommentRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_for_document_documents__document_id__comments_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                document_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CommentRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_for_document_documents__document_id__comments_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                document_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DocumentCommentCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CommentRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reply_comments__comment_id__replies_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                comment_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CommentReplyCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CommentRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_comments__comment_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                comment_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CommentUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CommentRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    search_projects__project_id__search_get: {
        parameters: {
            query: {
                q: string;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_export_transcripts__transcript_id__exports_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                transcript_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExportCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExportCreateResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_export_exports__export_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                export_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExportRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    download_export_exports__export_id__content_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                export_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_project_members_projects__project_id__members_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MemberRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    invite_projects__project_id__members_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MemberInvite"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MemberRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    remove_projects__project_id__members__user_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: string;
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    change_role_projects__project_id__members__user_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: string;
                project_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MemberRoleUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MemberRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_conversations_projects__project_id__chat_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChatConversationSummary"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ask_projects__project_id__chat_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChatAskRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_conversation_projects__project_id__chat__conversation_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                conversation_id: string;
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChatMessageRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_project_documents_projects__project_id__documents_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentSummary"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_projects__project_id__documents_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DocumentCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_documents__document_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                document_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_documents__document_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                document_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_documents__document_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                document_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DocumentUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    resolve_clip_block_route_documents__document_id__clip_blocks_resolve_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                document_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ClipBlockResolveRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClipBlockRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
