"""add segment project_id

Revision ID: 0561dc174ac1
Revises: afe0e73db43c
Create Date: 2026-09-18 16:59:21.305849

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0561dc174ac1"
down_revision: str | Sequence[str] | None = "afe0e73db43c"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Hand-adjusted: autogenerate produced `nullable=False` directly on
    # add_column, which fails against any existing row. Added nullable here,
    # backfilled from the owning transcript below, then set NOT NULL after —
    # the create_index/create_foreign_key calls were also lifted out of the
    # fenced block to run after the backfill, matching the column's final
    # (non-nullable) state.
    op.add_column("transcript_segments", sa.Column("project_id", sa.Uuid(), nullable=True))
    # ### end Alembic commands ###

    # Hand-written backfill: every existing segment's project_id is its own
    # transcript's project_id (segments never move between transcripts).
    op.execute(
        """
        UPDATE transcript_segments
        SET project_id = transcripts.project_id
        FROM transcripts
        WHERE transcript_segments.transcript_id = transcripts.id
        """
    )

    op.alter_column("transcript_segments", "project_id", nullable=False)
    op.create_index(
        op.f("ix_transcript_segments_project_id"),
        "transcript_segments",
        ["project_id"],
        unique=False,
    )
    op.create_foreign_key(
        op.f("fk_transcript_segments_project_id_projects"),
        "transcript_segments",
        "projects",
        ["project_id"],
        ["id"],
        ondelete="CASCADE",
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_transcript_segments_project_id_projects"),
        "transcript_segments",
        type_="foreignkey",
    )
    op.drop_index(op.f("ix_transcript_segments_project_id"), table_name="transcript_segments")
    op.drop_column("transcript_segments", "project_id")
    # ### end Alembic commands ###
