"""0011 transcript chunks and chat

Revision ID: 1513f71101d5
Revises: a6115182f8c0
Create Date: 2026-08-22 15:35:45.271203

"""

from collections.abc import Sequence

import pgvector.sqlalchemy
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "1513f71101d5"
down_revision: str | Sequence[str] | None = "a6115182f8c0"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # Hand-added (not autogenerated): the vector extension must exist before
    # transcript_chunks.embedding (a `vector` column) can be created below.
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "chat_conversations",
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("title", sa.String(), nullable=True),
        sa.Column("agent_message_history", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.Uuid(), nullable=False),
        sa.Column("updated_by", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by"], ["users.id"], name=op.f("fk_chat_conversations_created_by_users")
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_chat_conversations_project_id_projects"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["updated_by"], ["users.id"], name=op.f("fk_chat_conversations_updated_by_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_chat_conversations")),
    )
    op.create_index(
        op.f("ix_chat_conversations_project_id"), "chat_conversations", ["project_id"], unique=False
    )
    op.create_table(
        "chat_messages",
        sa.Column("conversation_id", sa.Uuid(), nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("role", sa.String(), nullable=False),
        sa.Column("content", sa.String(), nullable=False),
        sa.Column("citations", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("created_by", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["conversation_id"],
            ["chat_conversations.id"],
            name=op.f("fk_chat_messages_conversation_id_chat_conversations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["created_by"], ["users.id"], name=op.f("fk_chat_messages_created_by_users")
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_chat_messages_project_id_projects"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_chat_messages")),
    )
    op.create_index(
        op.f("ix_chat_messages_conversation_id"), "chat_messages", ["conversation_id"], unique=False
    )
    op.create_index(
        op.f("ix_chat_messages_project_id"), "chat_messages", ["project_id"], unique=False
    )
    op.create_table(
        "transcript_chunks",
        sa.Column("transcript_id", sa.Uuid(), nullable=False),
        sa.Column("video_id", sa.Uuid(), nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("language", sa.String(), nullable=True),
        sa.Column("segment_id", sa.Uuid(), nullable=False),
        sa.Column("start_token_id", sa.Uuid(), nullable=False),
        sa.Column("end_token_id", sa.Uuid(), nullable=False),
        sa.Column("start_time", sa.Float(), nullable=False),
        sa.Column("end_time", sa.Float(), nullable=False),
        sa.Column("speaker_name", sa.String(), nullable=True),
        sa.Column("chunk_index", sa.Integer(), nullable=False),
        sa.Column("text", sa.String(), nullable=False),
        sa.Column("search_vector", postgresql.TSVECTOR(), nullable=False),
        sa.Column("embedding", pgvector.sqlalchemy.Vector(1536), nullable=False),
        sa.Column("embedding_model", sa.String(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["end_token_id"],
            ["transcript_tokens.id"],
            name=op.f("fk_transcript_chunks_end_token_id_transcript_tokens"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_transcript_chunks_project_id_projects"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["segment_id"],
            ["transcript_segments.id"],
            name=op.f("fk_transcript_chunks_segment_id_transcript_segments"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["start_token_id"],
            ["transcript_tokens.id"],
            name=op.f("fk_transcript_chunks_start_token_id_transcript_tokens"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["transcript_id"],
            ["transcripts.id"],
            name=op.f("fk_transcript_chunks_transcript_id_transcripts"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["video_id"],
            ["videos.id"],
            name=op.f("fk_transcript_chunks_video_id_videos"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_transcript_chunks")),
    )
    op.create_index(
        "ix_transcript_chunks_embedding",
        "transcript_chunks",
        ["embedding"],
        unique=False,
        postgresql_using="hnsw",
        postgresql_ops={"embedding": "vector_cosine_ops"},
    )
    op.create_index(
        op.f("ix_transcript_chunks_project_id"), "transcript_chunks", ["project_id"], unique=False
    )
    op.create_index(
        "ix_transcript_chunks_search_vector",
        "transcript_chunks",
        ["search_vector"],
        unique=False,
        postgresql_using="gin",
    )
    op.create_index(
        op.f("ix_transcript_chunks_segment_id"), "transcript_chunks", ["segment_id"], unique=False
    )
    op.create_index(
        op.f("ix_transcript_chunks_transcript_id"),
        "transcript_chunks",
        ["transcript_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_transcript_chunks_video_id"), "transcript_chunks", ["video_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # Hand-added (not autogenerated): intentionally NOT dropping the `vector`
    # extension here — it's shared server state, not owned by this migration,
    # and leaving it installed is harmless.

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_transcript_chunks_video_id"), table_name="transcript_chunks")
    op.drop_index(op.f("ix_transcript_chunks_transcript_id"), table_name="transcript_chunks")
    op.drop_index(op.f("ix_transcript_chunks_segment_id"), table_name="transcript_chunks")
    op.drop_index(
        "ix_transcript_chunks_search_vector", table_name="transcript_chunks", postgresql_using="gin"
    )
    op.drop_index(op.f("ix_transcript_chunks_project_id"), table_name="transcript_chunks")
    op.drop_index(
        "ix_transcript_chunks_embedding",
        table_name="transcript_chunks",
        postgresql_using="hnsw",
        postgresql_ops={"embedding": "vector_cosine_ops"},
    )
    op.drop_table("transcript_chunks")
    op.drop_index(op.f("ix_chat_messages_project_id"), table_name="chat_messages")
    op.drop_index(op.f("ix_chat_messages_conversation_id"), table_name="chat_messages")
    op.drop_table("chat_messages")
    op.drop_index(op.f("ix_chat_conversations_project_id"), table_name="chat_conversations")
    op.drop_table("chat_conversations")
    # ### end Alembic commands ###
