"""0003 denormalize project_id

Revision ID: 1fc6e31c90bf
Revises: e4354408f955
Create Date: 2026-07-19 15:04:33.582110

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1fc6e31c90bf"
down_revision: str | Sequence[str] | None = "e4354408f955"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("processing_jobs", sa.Column("project_id", sa.Uuid(), nullable=True))
    op.create_index(
        op.f("ix_processing_jobs_project_id"), "processing_jobs", ["project_id"], unique=False
    )
    op.create_foreign_key(
        op.f("fk_processing_jobs_project_id_projects"),
        "processing_jobs",
        "projects",
        ["project_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.add_column("videos", sa.Column("project_id", sa.Uuid(), nullable=False))
    op.create_index(op.f("ix_videos_project_id"), "videos", ["project_id"], unique=False)
    op.create_foreign_key(
        op.f("fk_videos_project_id_projects"),
        "videos",
        "projects",
        ["project_id"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("fk_videos_project_id_projects"), "videos", type_="foreignkey")
    op.drop_index(op.f("ix_videos_project_id"), table_name="videos")
    op.drop_column("videos", "project_id")
    op.drop_constraint(
        op.f("fk_processing_jobs_project_id_projects"), "processing_jobs", type_="foreignkey"
    )
    op.drop_index(op.f("ix_processing_jobs_project_id"), table_name="processing_jobs")
    op.drop_column("processing_jobs", "project_id")
    # ### end Alembic commands ###
