"""0005 comments

Revision ID: 3caf3f9ffb4d
Revises: 6f8a0f577408
Create Date: 2026-07-19 17:08:38.466241

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "3caf3f9ffb4d"
down_revision: str | Sequence[str] | None = "6f8a0f577408"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "comments",
        sa.Column("transcript_id", sa.Uuid(), nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("text", sa.String(), nullable=False),
        sa.Column("resolved", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.Uuid(), nullable=False),
        sa.Column("updated_by", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by"], ["users.id"], name=op.f("fk_comments_created_by_users")
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_comments_project_id_projects"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["transcript_id"],
            ["transcripts.id"],
            name=op.f("fk_comments_transcript_id_transcripts"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["updated_by"], ["users.id"], name=op.f("fk_comments_updated_by_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_comments")),
    )
    op.create_index(op.f("ix_comments_project_id"), "comments", ["project_id"], unique=False)
    op.create_index(op.f("ix_comments_transcript_id"), "comments", ["transcript_id"], unique=False)
    op.create_table(
        "comment_replies",
        sa.Column("comment_id", sa.Uuid(), nullable=False),
        sa.Column("created_by", sa.Uuid(), nullable=False),
        sa.Column("text", sa.String(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["comment_id"],
            ["comments.id"],
            name=op.f("fk_comment_replies_comment_id_comments"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["created_by"], ["users.id"], name=op.f("fk_comment_replies_created_by_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_comment_replies")),
    )
    op.create_index(
        op.f("ix_comment_replies_comment_id"), "comment_replies", ["comment_id"], unique=False
    )
    op.create_table(
        "comment_ranges",
        sa.Column("comment_id", sa.Uuid(), nullable=False),
        sa.Column("start_token_id", sa.Uuid(), nullable=False),
        sa.Column("end_token_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["comment_id"],
            ["comments.id"],
            name=op.f("fk_comment_ranges_comment_id_comments"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["end_token_id"],
            ["transcript_tokens.id"],
            name=op.f("fk_comment_ranges_end_token_id_transcript_tokens"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["start_token_id"],
            ["transcript_tokens.id"],
            name=op.f("fk_comment_ranges_start_token_id_transcript_tokens"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_comment_ranges")),
    )
    op.create_index(
        op.f("ix_comment_ranges_comment_id"), "comment_ranges", ["comment_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_comment_ranges_comment_id"), table_name="comment_ranges")
    op.drop_table("comment_ranges")
    op.drop_index(op.f("ix_comment_replies_comment_id"), table_name="comment_replies")
    op.drop_table("comment_replies")
    op.drop_index(op.f("ix_comments_transcript_id"), table_name="comments")
    op.drop_index(op.f("ix_comments_project_id"), table_name="comments")
    op.drop_table("comments")
    # ### end Alembic commands ###
