"""0013 processing job run_after

Revision ID: 40c8f343b314
Revises: 479610eef81b
Create Date: 2026-08-28 12:00:00.000000

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "40c8f343b314"
down_revision: str | Sequence[str] | None = "479610eef81b"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

# Hand-written rather than autogenerated: the shared dev database currently
# sits on a sibling feature branch's migration (document-builder's
# `1da165e0f316`, also based on `479610eef81b`) that this branch's checkout
# doesn't have, so `alembic revision --autogenerate` can't resolve the DB's
# current revision here. The change itself is a single trivial nullable
# column addition matching `ProcessingJob.run_after`
# (app/models/job.py) — safe to write by hand.


def upgrade() -> None:
    """Upgrade schema."""
    op.add_column(
        "processing_jobs", sa.Column("run_after", sa.DateTime(timezone=True), nullable=True)
    )


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_column("processing_jobs", "run_after")
