"""0012 generate embeddings job type

Revision ID: 479610eef81b
Revises: 1513f71101d5
Create Date: 2026-08-22 16:33:43.466716

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "479610eef81b"
down_revision: str | Sequence[str] | None = "1513f71101d5"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "processing_jobs",
        "type",
        existing_type=sa.VARCHAR(length=18),
        type_=sa.Enum(
            "extract_metadata",
            "generate_proxy",
            "generate_thumbnail",
            "generate_waveform",
            "extract_audio",
            "transcribe",
            "translate",
            "generate_embeddings",
            "export",
            "noop",
            name="jobtype",
            native_enum=False,
        ),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "processing_jobs",
        "type",
        existing_type=sa.Enum(
            "extract_metadata",
            "generate_proxy",
            "generate_thumbnail",
            "generate_waveform",
            "extract_audio",
            "transcribe",
            "translate",
            "generate_embeddings",
            "export",
            "noop",
            name="jobtype",
            native_enum=False,
        ),
        type_=sa.VARCHAR(length=18),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
