"""0004 transcripts speakers

Revision ID: 6f8a0f577408
Revises: 1fc6e31c90bf
Create Date: 2026-07-19 16:11:57.036437

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "6f8a0f577408"
down_revision: str | Sequence[str] | None = "1fc6e31c90bf"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "speakers",
        sa.Column("video_id", sa.Uuid(), nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("provider_identifier", sa.String(), nullable=True),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("color", sa.String(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_speakers_project_id_projects"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["video_id"],
            ["videos.id"],
            name=op.f("fk_speakers_video_id_videos"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_speakers")),
    )
    op.create_index(op.f("ix_speakers_project_id"), "speakers", ["project_id"], unique=False)
    op.create_index(op.f("ix_speakers_video_id"), "speakers", ["video_id"], unique=False)
    op.create_table(
        "transcripts",
        sa.Column("video_id", sa.Uuid(), nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("language", sa.String(), nullable=True),
        sa.Column(
            "type",
            sa.Enum("original", "translation", name="transcripttype", native_enum=False),
            nullable=False,
        ),
        sa.Column("provider_raw_response", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("created_by", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["created_by"], ["users.id"], name=op.f("fk_transcripts_created_by_users")
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_transcripts_project_id_projects"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["video_id"],
            ["videos.id"],
            name=op.f("fk_transcripts_video_id_videos"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_transcripts")),
    )
    op.create_index(op.f("ix_transcripts_project_id"), "transcripts", ["project_id"], unique=False)
    op.create_index(op.f("ix_transcripts_video_id"), "transcripts", ["video_id"], unique=False)
    op.create_table(
        "transcript_segments",
        sa.Column("transcript_id", sa.Uuid(), nullable=False),
        sa.Column("speaker_id", sa.Uuid(), nullable=True),
        sa.Column("position", sa.Numeric(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["speaker_id"],
            ["speakers.id"],
            name=op.f("fk_transcript_segments_speaker_id_speakers"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["transcript_id"],
            ["transcripts.id"],
            name=op.f("fk_transcript_segments_transcript_id_transcripts"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_transcript_segments")),
    )
    op.create_index(
        op.f("ix_transcript_segments_speaker_id"),
        "transcript_segments",
        ["speaker_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_transcript_segments_transcript_id"),
        "transcript_segments",
        ["transcript_id"],
        unique=False,
    )
    op.create_table(
        "transcript_tokens",
        sa.Column("transcript_id", sa.Uuid(), nullable=False),
        sa.Column("segment_id", sa.Uuid(), nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("original_text", sa.String(), nullable=False),
        sa.Column("edited_text", sa.String(), nullable=True),
        sa.Column("start_time", sa.Float(), nullable=False),
        sa.Column("end_time", sa.Float(), nullable=False),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("position", sa.Numeric(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.Uuid(), nullable=False),
        sa.Column("updated_by", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by"], ["users.id"], name=op.f("fk_transcript_tokens_created_by_users")
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_transcript_tokens_project_id_projects"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["segment_id"],
            ["transcript_segments.id"],
            name=op.f("fk_transcript_tokens_segment_id_transcript_segments"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["transcript_id"],
            ["transcripts.id"],
            name=op.f("fk_transcript_tokens_transcript_id_transcripts"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["updated_by"], ["users.id"], name=op.f("fk_transcript_tokens_updated_by_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_transcript_tokens")),
    )
    op.create_index(
        op.f("ix_transcript_tokens_project_id"), "transcript_tokens", ["project_id"], unique=False
    )
    op.create_index(
        op.f("ix_transcript_tokens_segment_id"), "transcript_tokens", ["segment_id"], unique=False
    )
    op.create_index(
        op.f("ix_transcript_tokens_transcript_id"),
        "transcript_tokens",
        ["transcript_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_transcript_tokens_transcript_id"), table_name="transcript_tokens")
    op.drop_index(op.f("ix_transcript_tokens_segment_id"), table_name="transcript_tokens")
    op.drop_index(op.f("ix_transcript_tokens_project_id"), table_name="transcript_tokens")
    op.drop_table("transcript_tokens")
    op.drop_index(op.f("ix_transcript_segments_transcript_id"), table_name="transcript_segments")
    op.drop_index(op.f("ix_transcript_segments_speaker_id"), table_name="transcript_segments")
    op.drop_table("transcript_segments")
    op.drop_index(op.f("ix_transcripts_video_id"), table_name="transcripts")
    op.drop_index(op.f("ix_transcripts_project_id"), table_name="transcripts")
    op.drop_table("transcripts")
    op.drop_index(op.f("ix_speakers_video_id"), table_name="speakers")
    op.drop_index(op.f("ix_speakers_project_id"), table_name="speakers")
    op.drop_table("speakers")
    # ### end Alembic commands ###
