"""0009 membership roles

Revision ID: 94d178107195
Revises: f0aad2de47b4
Create Date: 2026-07-22 16:58:53.432225

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "94d178107195"
down_revision: str | Sequence[str] | None = "f0aad2de47b4"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # HAND-EDITED: autogenerate produced `nullable=False` directly, which would
    # fail on any pre-existing membership rows. Changed to `nullable=True` here
    # so the column can be added first, backfilled below, then tightened to
    # NOT NULL by a hand-added `alter_column` (existing project creators all
    # become OWNER, matching how `create_project` already grants the creator
    # ownership).
    op.add_column(
        "project_memberships",
        sa.Column(
            "role",
            sa.Enum("owner", "editor", "viewer", name="membershiprole", native_enum=False),
            nullable=True,
        ),
    )
    # ### end Alembic commands ###

    # HAND-ADDED: backfill existing rows before tightening to NOT NULL below.
    op.execute("UPDATE project_memberships SET role = 'owner' WHERE role IS NULL")

    # HAND-ADDED: not part of autogenerate output — tightens the column added
    # above to NOT NULL now that every existing row has been backfilled.
    op.alter_column("project_memberships", "role", nullable=False)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("project_memberships", "role")
    # ### end Alembic commands ###
