"""0010 token version

Revision ID: a6115182f8c0
Revises: 94d178107195
Create Date: 2026-07-22 18:16:28.301451

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a6115182f8c0"
down_revision: str | Sequence[str] | None = "94d178107195"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "transcript_tokens", sa.Column("version", sa.Integer(), server_default="1", nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("transcript_tokens", "version")
    # ### end Alembic commands ###
