"""add token is_highlighted

Revision ID: afe0e73db43c
Revises: f535f53bb33e
Create Date: 2026-09-18 16:40:38.935336

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "afe0e73db43c"
down_revision: str | Sequence[str] | None = "f535f53bb33e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "transcript_tokens",
        sa.Column("is_highlighted", sa.Boolean(), server_default="false", nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("transcript_tokens", "is_highlighted")
    # ### end Alembic commands ###
