"""0006 search vectors

Revision ID: d4c468bbac92
Revises: 3caf3f9ffb4d
Create Date: 2026-07-19 17:23:22.328723

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "d4c468bbac92"
down_revision: str | Sequence[str] | None = "3caf3f9ffb4d"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "comments",
        sa.Column(
            "search_vector",
            postgresql.TSVECTOR(),
            sa.Computed("to_tsvector('english', text)", persisted=True),
            nullable=False,
        ),
    )
    op.create_index(
        "ix_comments_search_vector",
        "comments",
        ["search_vector"],
        unique=False,
        postgresql_using="gin",
    )
    op.add_column(
        "speakers",
        sa.Column(
            "search_vector",
            postgresql.TSVECTOR(),
            sa.Computed("to_tsvector('english', coalesce(name, ''))", persisted=True),
            nullable=False,
        ),
    )
    op.create_index(
        "ix_speakers_search_vector",
        "speakers",
        ["search_vector"],
        unique=False,
        postgresql_using="gin",
    )
    op.add_column(
        "transcript_tokens",
        sa.Column(
            "search_vector",
            postgresql.TSVECTOR(),
            sa.Computed(
                "to_tsvector('english', coalesce(edited_text, original_text))", persisted=True
            ),
            nullable=False,
        ),
    )
    op.create_index(
        "ix_transcript_tokens_search_vector",
        "transcript_tokens",
        ["search_vector"],
        unique=False,
        postgresql_using="gin",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_transcript_tokens_search_vector", table_name="transcript_tokens", postgresql_using="gin"
    )
    op.drop_column("transcript_tokens", "search_vector")
    op.drop_index("ix_speakers_search_vector", table_name="speakers", postgresql_using="gin")
    op.drop_column("speakers", "search_vector")
    op.drop_index("ix_comments_search_vector", table_name="comments", postgresql_using="gin")
    op.drop_column("comments", "search_vector")
    # ### end Alembic commands ###
