"""0008 generate thumbnail job type

Revision ID: f0aad2de47b4
Revises: 2cd6af4f89bd
Create Date: 2026-07-21 10:12:28.808391

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f0aad2de47b4"
down_revision: str | Sequence[str] | None = "2cd6af4f89bd"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "processing_jobs",
        "type",
        existing_type=sa.VARCHAR(length=17),
        type_=sa.Enum(
            "extract_metadata",
            "generate_proxy",
            "generate_thumbnail",
            "generate_waveform",
            "extract_audio",
            "transcribe",
            "translate",
            "export",
            "noop",
            name="jobtype",
            native_enum=False,
        ),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "processing_jobs",
        "type",
        existing_type=sa.Enum(
            "extract_metadata",
            "generate_proxy",
            "generate_thumbnail",
            "generate_waveform",
            "extract_audio",
            "transcribe",
            "translate",
            "export",
            "noop",
            name="jobtype",
            native_enum=False,
        ),
        type_=sa.VARCHAR(length=17),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
