"""0014 document comments

Revision ID: f535f53bb33e
Revises: e4d53a25eb4a
Create Date: 2026-08-29 00:47:00.246494

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f535f53bb33e"
down_revision: str | Sequence[str] | None = "e4d53a25eb4a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "document_comment_anchors",
        sa.Column("comment_id", sa.Uuid(), nullable=False),
        sa.Column("clip_node_id", sa.String(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["comment_id"],
            ["comments.id"],
            name=op.f("fk_document_comment_anchors_comment_id_comments"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_document_comment_anchors")),
    )
    op.create_index(
        op.f("ix_document_comment_anchors_comment_id"),
        "document_comment_anchors",
        ["comment_id"],
        unique=True,
    )
    op.add_column("comments", sa.Column("document_id", sa.Uuid(), nullable=True))
    op.alter_column("comments", "transcript_id", existing_type=sa.UUID(), nullable=True)
    op.create_index(op.f("ix_comments_document_id"), "comments", ["document_id"], unique=False)
    op.create_foreign_key(
        op.f("fk_comments_document_id_documents"),
        "comments",
        "documents",
        ["document_id"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###

    # Hand-added: Alembic's autogenerate never diffs CHECK constraints (no
    # comparator for them exists in alembic.autogenerate.compare, regardless
    # of naming convention) — this is a documented tool limitation, not a
    # model/naming issue to "fix and regenerate". The model
    # (app/models/comment.py) is still the source of truth; this statement
    # mirrors it exactly. Pass the bare constraint name (not pre-expanded) —
    # op.create_check_constraint applies NAMING_CONVENTION's "ck" template
    # itself, same as the model does, producing `ck_comments_exactly_one_anchor`.
    op.create_check_constraint(
        "exactly_one_anchor",
        "comments",
        "(transcript_id IS NULL) != (document_id IS NULL)",
    )


def downgrade() -> None:
    """Downgrade schema."""
    # Hand-added: reverse the hand-added CHECK constraint above (Alembic never
    # autogenerates a downgrade for it either, for the same reason). Same bare
    # name as upgrade() — op.drop_constraint applies the naming convention too.
    op.drop_constraint("exactly_one_anchor", "comments", type_="check")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("fk_comments_document_id_documents"), "comments", type_="foreignkey")
    op.drop_index(op.f("ix_comments_document_id"), table_name="comments")
    op.alter_column("comments", "transcript_id", existing_type=sa.UUID(), nullable=False)
    op.drop_column("comments", "document_id")
    op.drop_index(
        op.f("ix_document_comment_anchors_comment_id"), table_name="document_comment_anchors"
    )
    op.drop_table("document_comment_anchors")
    # ### end Alembic commands ###
